### ISSUE TITLE
Search terms on one line blows up on arch

### ISSUE THREAD

**Issue by enewbury** [enewbury/workstation#4]
This:
```
- name: ssh config | lookup public key from 1password
      onepassword_info:
         search_terms: "id_ed25519.pub"
      register: id_ed25519_pub_info
```
Needs to become this:
```
- name: ssh config | lookup public key from 1password
        onepassword_info:
          search_terms: 
              - "id_ed25519.pub"
        register: id_ed25519_pub_info
```
