### ISSUE TITLE
Add caps2escape

### ISSUE THREAD

**Issue by enewbury** [enewbury/workstation#8]
I like to tap capslock to escape and hold for control.  Setup this repo
https://gitlab.com/interception/linux/plugins/caps2esc
Config /etc/interception/udevmon.d/keyboards.yaml 
```
- JOB: intercept -g $DEVNODE | caps2esc | uinput -d $DEVNODE 
  DEVICE:
    EVENTS:
      EV_KEY: [KEY_CAPSLOCK, KEY_ESC]

```
